# Generated by Django 4.0.5 on 2022-11-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs_work', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersLog',
            new_name='AuthorLog',
        ),
    ]
