# Generated by Django 4.0.5 on 2022-11-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs_work', '0004_userlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorlog',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorLog',
        ),
    ]
